/** This file is auto-generated by Plasmic; please do not edit! */
import { useRouter } from "next/router";
import PlasmicLoader from "@plasmicapp/loader";

const componentsByPath = {
  
    "tours": {name: "Tours", projectId: "9eiWo8Eadwtw46zacr9r4i" },
  
    "login": {name: "Login", projectId: "9eiWo8Eadwtw46zacr9r4i" },
  
    "tour-creator": {name: "TourCreator", projectId: "9eiWo8Eadwtw46zacr9r4i" },
  
};

export default function PlasmicLoaderPage() {
  const router = useRouter();
  let { plasmicLoaderPage } = router.query;
  if (Array.isArray(plasmicLoaderPage)) {
    plasmicLoaderPage = plasmicLoaderPage.join('/');
  }
  const {name, projectId} = componentsByPath[plasmicLoaderPage];

  return <PlasmicLoader component={name} projectId={projectId} />;
}

export async function getStaticProps() {
  return {
    props: {},
  };
}

export async function getStaticPaths() {
  return {
    paths: [
      
        { params: { plasmicLoaderPage: ["tours",] } },
      
        { params: { plasmicLoaderPage: ["login",] } },
      
        { params: { plasmicLoaderPage: ["tour-creator",] } },
      
    ],
    fallback: false,
  };
}
